Clients
ThyArt/thyart-web pull request #63
Opened 2019-11-16 23:48 UTC by PierreMigani

2019-11-18 21:55 UTC, jean-gblr requested changes
Required pour merge :

- couleur de validation form
- corriger les warnings

Pour la culture:

- Apprendre a utiliser Map
- Key, setKey c'est vraiment sale

2019-11-18 21:55 UTC, jean-gblr commented on src/components/Form/Form.jsx
> +import React, { Fragment } from 'react';
unused fragment

2019-11-18 21:55 UTC, jean-gblr commented on src/views/ClientForm.js
> +                <TextField
Changer la couleur en cas d'email non valide, actuellement rien ne se passe

2019-11-18 21:55 UTC, jean-gblr commented on src/views/ClientForm.js
> +                <TextField id="phone" label="Téléphone" name="phone" value={number.value} onChange={e => onChange(e, setNumber, validateNumber)} required />
Pareil que pour email

2019-11-18 21:55 UTC, jean-gblr commented on src/views/Clients.js
> +    const [key, setKey] = useState(Math.random());
C'est sale, mais j'ai pas le temps de fix

2019-11-18 21:55 UTC, jean-gblr commented on src/views/ClientDetails.js
> +                    <ListItem alignItems="flex-start">
ici au lieu de répéter des elements tu peux faire un const des variables, et ensuite .map

2019-11-18 21:57 UTC, jean-gblr commented
<img width="1222" alt="Screen Shot 2019-11-18 at 22 56 57" src="https://user-images.githubusercontent.com/36892393/69097436-d548ba80-0a56-11ea-9067-8cfaa1e21836.png">

2019-11-20 22:58 UTC, PierreMigani commented
j'ai fait un commit avec les fix (sauf pour le problème de setKey)

2019-11-23 13:45 UTC, jean-gblr requested changes

2019-11-23 13:45 UTC, jean-gblr commented on src/views/ClientDetails.js
> +    const { isNew, clientId, returnFunction } = props;
il manque les proptypes pour les props que tu utilisent, à ajouter en bas de fichier :)

2019-11-23 13:45 UTC, jean-gblr commented on src/views/ClientForm.js
> +    let { client, isNew, returnFunction } = props;
ajouter les prop types, idem que dans clientdetails

2019-11-23 13:49 UTC, jean-gblr commented
J'ai fais quelques modifs, il te reste juste a ajouter les prop types et c'est bon

2019-11-24 21:20 UTC, PierreMigani commented
j'ai rebase la branche

2019-11-25 09:47 UTC, merged